// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzlmw0w0t99jltAZ2_fC-Qs1LIF8P4cqY',
    appId: '1:951319114818:web:e9a49e89de1f8fe5f869db',
    messagingSenderId: '951319114818',
    projectId: 'inventorysystem-ae4d5',
    authDomain: 'inventorysystem-ae4d5.firebaseapp.com',
    storageBucket: 'inventorysystem-ae4d5.firebasestorage.app',
    measurementId: 'G-9KEPN8SX3Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD4d_T3Mp3VsoyMhVQyubgv8-BIJtFQF8',
    appId: '1:951319114818:android:c2099a5ff4d046f5f869db',
    messagingSenderId: '951319114818',
    projectId: 'inventorysystem-ae4d5',
    storageBucket: 'inventorysystem-ae4d5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR47yU1LjJENBeYdl-aZyk-AyI0-b4H2w',
    appId: '1:951319114818:ios:51e7e87e87e1f662f869db',
    messagingSenderId: '951319114818',
    projectId: 'inventorysystem-ae4d5',
    storageBucket: 'inventorysystem-ae4d5.firebasestorage.app',
    iosBundleId: 'com.inventorysystem.inventroysystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAR47yU1LjJENBeYdl-aZyk-AyI0-b4H2w',
    appId: '1:951319114818:ios:51e7e87e87e1f662f869db',
    messagingSenderId: '951319114818',
    projectId: 'inventorysystem-ae4d5',
    storageBucket: 'inventorysystem-ae4d5.firebasestorage.app',
    iosBundleId: 'com.inventorysystem.inventroysystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzlmw0w0t99jltAZ2_fC-Qs1LIF8P4cqY',
    appId: '1:951319114818:web:3503a4c5b7eb5bdcf869db',
    messagingSenderId: '951319114818',
    projectId: 'inventorysystem-ae4d5',
    authDomain: 'inventorysystem-ae4d5.firebaseapp.com',
    storageBucket: 'inventorysystem-ae4d5.firebasestorage.app',
    measurementId: 'G-5WKN1C13YF',
  );
}
